### ISSUE TITLE
Website No Longer Working?

### ISSUE THREAD

**Issue by The13thDoctors** [AguzzTN54/Genshin-Impact-Wish-Simulator#45] opened 2022-11-05 00:48 UTC
![why](https://user-images.githubusercontent.com/117492361/200093439-2aca6be3-63d6-4195-86c1-b19ecfff0571.JPG)

I can no longer get onto the website. Is it down or something? It's been like this for a long while for me. Is there something I need to fix on my end? Or is this something that's not working on your end?

**Comment by AguzzTN54** [comment] 2022-11-05 05:49
The site is still alive, so I assume that the error occurs because the browser can't verify the SSL certificate. Please try to open it in Private/Incognito Mode or try with another browser.
If it still doesn't load, maybe this article can help you [http://woshub.com/ssl-error-site-cant-provide-secure-connection/](http://woshub.com/ssl-error-site-cant-provide-secure-connection/)

**Comment by The13thDoctors** [comment] 2022-11-05 06:28
I've tried everything and none of the solutions worked. It also doesn't work on my Chromebook but works on my phone. I am very confused. :v

**Comment by The13thDoctors** [comment] 2022-11-05 06:31
![butwhy](https://user-images.githubusercontent.com/117492361/200106251-331cbb9d-9515-4cfd-8e23-6f4f9e1a4a01.JPG)

**Comment by AguzzTN54** [comment] 2022-11-05 07:40
> ![butwhy](https://user-images.githubusercontent.com/117492361/200106251-331cbb9d-9515-4cfd-8e23-6f4f9e1a4a01.JPG)

Is this captured from a different browser?
Sorry I'm use Cloudflare to host the site, the SSL configuration is automatically managed by Cloudflare, so I can't modify it.
You can try some alternative sites like [wishsimulator.pages.dev](https://wishsimulator.pages.dev), [gacha.miraaaa.my.id](https://gacha.miraaaa.my.id/) , [genshinwishsimulator.genshindc.com](https://genshinwishsimulator.genshindc.com/) . But I'm not sure they are always updated, because they are take the source code from this repository and not managed by me .

**Comment by The13thDoctors** [comment] 2022-11-05 07:45
The other website links worked, thanks! Also to answer your question, the first screenshot was from Chrome and the second was from Firefox. Windows Edge also was a no-go.

**Comment by AguzzTN54** [comment] 2022-11-05 09:11
Ok then .. just use alternative sites for a while, wishsimulator.pages.dev and public-genshin-wish.vercel.app are always updated with the latest banners too.

Btw. Thanks for your feedback, I don't think this problem is caused by the server, I'll close this issue for now.

**Closed by AguzzTN54** 2022-11-05 09:11 UTC
